version: '3.7'

services:
  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: python bot.py
    restart: always
    stop_signal: SIGINT
    build:
      context: .
    env_file:
      - ".env"
    depends_on:
      - db
  redis:
    image: "redis:alpine"
    restart: always
    volumes:
      - ./redisdata:/var/lib/redis
    expose:
      - 6379
  db:
    image: postgres:14.4-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - ./.env
    ports:
      - 0.0.0.0:${DB_ONLINE_PORT}:5432
    expose:
      - 5432
  atl_url_server:
    image: ghcr.io/whiteapfel/pyqiwip2p:p2proxy
    container_name: atl_url_server_info_bot
    ports:
      - 3600:3600

networks:
  overlay:

volumes:
  postgres_data: